eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: order
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/order/**
          filters: AuthenticationFilter
        - id: product
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/product/**
          filters: AuthenticationFilter
        - id: security
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/security/**

management:
  tracing:
    sampling:
      probability: 1.0