eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # Add this to help with registration
server:
  port: 8091
spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: Malathi75
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
application:
  config:
    students-url: http://localhost:8091/api/v1/order
  logging:
    level:
      com.netflix.discovery: DEBUG
      org.springframework.cloud.netflix.eureka: DEBUG
management:
  tracing:
    sampling:
      probability: 1.0