eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # Add this to help with registration

server:
  port: 8095

spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    username: root
    password: Malathi75
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 312779466340-l07cq4doej31j3b9rdpth71juj4l2d8t.apps.googleusercontent.com
            client-secret: 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
            scope: openid,email,profile
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google

application:
  config:
    students-url: http://localhost:8095/api/v1/security
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  logging:
    level:
      com.netflix.discovery: DEBUG
      org.springframework.cloud.netflix.eureka: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0