eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # Add this to help with registration
server:
  port: 8090
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: Malathi75
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect
application:
  config:
    students-url: http://localhost:8090/api/v1/user
management:
  tracing:
    sampling:
      probability: 1.0